server:
  port: 8081

#logging:
#  level:
#    root: debug


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/likelion
      username: root
      password: password